<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1iLidzG\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1iLidzG/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container1iLidzG.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container1iLidzG\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container1iLidzG\App_KernelDevDebugContainer([
    'container.build_hash' => '1iLidzG',
    'container.build_id' => '506122dd',
    'container.build_time' => 1778266940,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container1iLidzG');
